import {test} from 'node:test';
import assert from 'node:assert/strict';
import {buildBookingHandoff,friendlyBookingUrl,bookingDay} from '../js/core/bookingHandoff.js';
const products=[{id:'linen',external_id:'fpr:sequin-linen',active:true},{id:'tent',external_id:'fpr:20x20-pole-tent',active:true}],base={tenant:'friendly',products,eventDate:'2099-06-01',source:'home_designer_section'};
test('known identities transfer without any copied or guessed dollar amount',()=>{const p=buildBookingHandoff({...base,lines:[{productId:'tent',label:'Tent',qty:1,amount:null},{productId:'linen',label:'Linen',qty:2,amount:999,selectedColor:'Rose Gold'}],deliveryZip:'13116'});assert.equal(p.items.length,2);assert.equal(p.items[1].selectedColor,'Rose Gold');assert.equal(p.items[1].quantity,2);assert.equal(p.items[1].amount,undefined);assert.equal(p.deliveryZip,'13116');assert.equal(new URL(friendlyBookingUrl(p)).pathname,'/design-your-event/book');assert.equal(new URL(friendlyBookingUrl(p)).searchParams.get('auto'),'1');});
test('exact variants merge independently; taxes are recalculated in Friendly',()=>{const p=buildBookingHandoff({...base,lines:[{productId:'linen',qty:2,selectedColor:'Silver'},{productId:'linen',qty:3,selectedColor:'Silver'},{productId:'linen',qty:1,selectedColor:'Rose Gold'},{category:'tax',qty:1,amount:42}]});assert.deepEqual(p.items.map(i=>[i.selectedColor,i.quantity]),[['Silver',5],['Rose Gold',1]]);});
test('unmatched identity blocks complete transfer instead of dropping rentals',()=>{assert.throws(()=>buildBookingHandoff({...base,lines:[{productId:'tent',qty:1},{productId:'missing',qty:2,label:'Unknown rental'}]}),/Unknown rental.*no item will be left out/);});
test('cross-tenant, hostile slug, duplicate identities and invalid quantities fail',()=>{assert.throws(()=>buildBookingHandoff({...base,tenant:'other',lines:[{productId:'tent',qty:1}]}));assert.throws(()=>buildBookingHandoff({...base,products:[products[0],products[0]],lines:[{productId:'linen',qty:1}]}));for(const qty of [0,-1,1.5,1001])assert.throws(()=>buildBookingHandoff({...base,lines:[{productId:'tent',qty}]}));});
test('date validation is calendar-real and handoff has no contact or payment tokens',()=>{assert.equal(bookingDay('2099-02-30'),'');assert.equal(bookingDay('2099-06-01'),'2099-06-01');const p=buildBookingHandoff({...base,lines:[{productId:'tent',qty:1}],email:'secret@example.invalid',token:'private',unitPrice:1});assert.equal(p.email,undefined);assert.equal(p.token,undefined);assert.equal(p.unitPrice,undefined);});
