// Read-only public fixtures and local WebGL source. No orders/payments/emails.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const root=path.resolve(__dirname,'..'),out=root+'/qa-phase5';
(async()=>{
 const manifest=JSON.parse(fs.readFileSync(out+'/manifest.json')),catalog=JSON.parse(fs.readFileSync(out+'/catalog.json'));
 const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');let data=fs.readFileSync(file);if(file.endsWith('catalog-preview/index.html'))data=Buffer.from(data.toString().replaceAll('https://cdn.jsdelivr.net/npm/three@0.160.0/','/tests/node_modules/three/'));res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.js')?'text/javascript':file.endsWith('.json')?'application/json':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(data);}catch{res.writeHead(404).end();}}).listen(8127,'127.0.0.1');
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}),page=await browser.newPage({viewport:{width:800,height:640}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.hostname==='127.0.0.1')return route.continue();if(url.hostname==='rentsketch-api-production.up.railway.app'&&url.pathname==='/api/tenants/friendly/products')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(catalog)});return route.abort();});
 fs.mkdirSync(out+'/rendered',{recursive:true});fs.mkdirSync(out+'/browser',{recursive:true});
 await page.goto('http://127.0.0.1:8127/tests/phase5-harness.html');await page.waitForFunction(()=>window.ready===true,{timeout:20000});const rendered=[];
 for(const p of manifest.products){const result=await page.evaluate(id=>window.renderProduct(id),p.id);rendered.push({...p,...result});if(result.supported)await page.screenshot({path:out+'/rendered/'+p.slug+'.png'});}
 const views=[];
 for(const width of [900,320])for(const p of rendered){await page.setViewportSize({width,height:620});await page.goto('http://127.0.0.1:8127/catalog-preview/?tenant=friendly&productId='+p.id);
  if(p.supported){await page.waitForFunction(()=>document.getElementById('visual').dataset.renderReady==='1',{timeout:15000});assert.equal(await page.locator('canvas').count(),1);}
  else{await page.waitForFunction(()=>document.getElementById('status').textContent==='Reference conflict — no verified model');assert.equal(await page.locator('canvas').count(),0);}
  const state=await page.evaluate(()=>({productId:document.getElementById('visual').dataset.productId||null,overflow:document.documentElement.scrollWidth>innerWidth+1,status:document.getElementById('status').textContent}));assert.equal(state.overflow,false);if(p.supported)assert.equal(state.productId,p.id);views.push({slug:p.slug,width,supported:p.supported,...state});
  if(['4375-watt-generator','30a-power-distribution-spider-box','battery-operated-crystal-chandelier','stage-ramp','dance-floor-3x3-section'].includes(p.slug))await page.screenshot({path:out+'/browser/'+p.slug+'-'+width+'.png'});
  const installed=page.getByRole('button',{name:'Show installed example'});if(await installed.count()){await installed.click();await page.waitForFunction(()=>document.getElementById('visual').dataset.renderReady==='1');assert.equal(await page.locator('canvas').count(),1);if(width===900)await page.screenshot({path:out+'/browser/'+p.slug+'-installed.png'});await page.getByRole('button',{name:'Show hardware detail'}).click();assert.equal(await page.locator('canvas').count(),1);}
 }
 await page.goto('http://127.0.0.1:8127/catalog-preview/?tenant=friendly&productId=unknown');await page.waitForFunction(()=>document.getElementById('status').textContent==='Preview unavailable');assert.equal(await page.locator('canvas').count(),0);
 assert.deepEqual(errors,[]);const report={rendered,views,errors,realOrdersCreated:0,realPaymentsSubmitted:0,checkedAt:new Date().toISOString()};fs.writeFileSync(out+'/browser-report.json',JSON.stringify(report,null,2));console.log('PASS '+rendered.filter(p=>p.supported).length+' actual model captures, '+views.length+' desktop/mobile product views, source conflicts explicitly unrendered; no errors/overflow.');await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
