// Only public reads. Browser-local selections are destroyed after verification.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {pathToFileURL}=require('node:url'),{chromium}=require('playwright');
const RS='https://rentsketch.com',FPR='https://www.friendlypartyrental.com',API='https://rentsketch-api-production.up.railway.app',OUT='qa-phase6b-live',release=process.env.RELEASE_SHA;
(async()=>{
 assert.match(release||'',/^[a-f0-9]{40}$/);fs.mkdirSync(OUT,{recursive:true});const load=p=>import(pathToFileURL(path.resolve(p))),read=async u=>{const r=await fetch(u,{signal:AbortSignal.timeout(20000)});assert.ok(r.ok,u);return r.json();};
 const {PHASE6B_SLUGS,phase6bReference}=await load('js/data/phase6b-reference.js'),{equipmentCatalog,equipmentItem}=await load('js/data/equipment.js'),{tabletopCatalog}=await load('js/data/tabletop.js'),{liveCatalog}=await load('js/data/catalog.js'),{TABLES}=await load('js/data/tables.js'),{summarizeEvent}=await load('js/core/eventSummary.js'),{buildBookingHandoff,friendlyBookingUrl}=await load('js/core/bookingHandoff.js');
 const products=(await read(API+'/api/tenants/friendly/products')).products;const dt=new Date();dt.setUTCDate(dt.getUTCDate()+28);const date=dt.toISOString().slice(0,10),website=(await read(FPR+'/api/items?date='+date+'T12%3A00%3A00')).items;
 const conflicts=['glass-water-pitcher-64-oz','round-gold-metal-display-dish','hexagon-wedding-arch'];
 const identities=PHASE6B_SLUGS.map(slug=>{const pp=products.filter(p=>p.external_id==='fpr:'+slug&&p.active!==false),ww=website.filter(p=>p.slug===slug);assert.equal(pp.length,1,slug+' tenant identity');assert.equal(ww.length,1,slug+' website identity');const ref=phase6bReference(pp[0]);assert.equal(ref.kind==='reference-only',conflicts.includes(slug));const handoff=buildBookingHandoff({tenant:'friendly',products,lines:[{productId:pp[0].id,qty:2,label:pp[0].name}],eventDate:date});assert.equal(handoff.items.length,1);assert.equal(handoff.items[0].slug,slug);assert.equal(handoff.items[0].quantity,2);return{slug,productId:pp[0].id,websiteItemId:ww[0].id,referenceOnly:ref.kind==='reference-only',placement:ref.kind};});
 const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}),errors=[],blocked=[],views=[];
 async function context(width){const c=await browser.newContext({viewport:{width,height:800},serviceWorkers:'block'});await c.route('**/*',route=>{const r=route.request(),u=new URL(r.url());if(!['GET','HEAD'].includes(r.method())){blocked.push({method:r.method(),path:u.pathname});return route.fulfill({status:200,contentType:'application/json',body:'{"ok":true,"skipped":true}'});}if(/google-analytics|googletagmanager|doubleclick|googleadservices|facebook\.com|facebook\.net/.test(u.hostname))return route.abort();return route.continue();});return c;}
 try{
  for(const width of [1000,390]){const c=await context(width),p=await c.newPage();p.on('pageerror',e=>errors.push({width,error:String(e)}));
   for(const row of identities){await p.goto(RS+'/catalog-preview/?tenant=friendly&productId='+row.productId,{waitUntil:'domcontentloaded'});
    if(row.referenceOnly){await p.waitForFunction(()=>document.getElementById('status').textContent==='Reference conflict — no verified model',null,{timeout:25000});assert.equal(await p.locator('canvas').count(),0);}else{await p.waitForFunction(()=>document.getElementById('visual').dataset.renderReady==='1',null,{timeout:30000});assert.equal(await p.locator('canvas').count(),1);assert.equal(await p.locator('#visual').getAttribute('data-product-id'),row.productId);}
    assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);views.push({slug:row.slug,width,liveModel:!row.referenceOnly,noOverflow:true});
    if(['8-quart-full-size-chafer','audio-guest-book','sequin-backdrop-panel-8x8','hexagon-wedding-arch'].includes(row.slug))await p.screenshot({path:OUT+'/'+row.slug+'-'+width+'.png'});
   }await c.close();
  }
  const desired=[['8-quart-full-size-chafer',2],['25-gallon-insulated-beverage-dispenser',1],['salt-and-pepper-shaker-set',1],['bus-bin',2],['audio-guest-book',1],['25-foot-movie-screen-with-projector',1],['movie-night-laptop-rental',1]];
  const bookable=(w,n)=>w&&w.displayToCustomer===true&&String(w.status).toLowerCase()==='available'&&Number(w.available??w.quantity)>=n&&w.cost!=null&&Number.isFinite(Number(w.cost))&&!(w.colorOptions||[]).length;
  const chosen=desired.filter(([slug,n])=>bookable(website.find(w=>w.slug===slug),n)),missing=desired.filter(([slug])=>!chosen.some(([s])=>s===slug));assert.ok(chosen.length>=5,'Require a meaningful currently bookable mixed serving/equipment selection');
  const supportP=products.find(p=>p.external_id==='fpr:6ft-plastic-folding-table'&&p.active!==false),supportW=website.find(w=>w.slug==='6ft-plastic-folding-table');assert.ok(supportP);assert.ok(bookable(supportW,1));const tables=liveCatalog('table',TABLES,products,false),support=tables.find(t=>t.productId===supportP.id);assert.ok(support);
  const equipment=equipmentCatalog(products,false),tabletop=tabletopCatalog(products,false),selected=chosen.map(([slug,qty])=>({p:products.find(p=>p.external_id==='fpr:'+slug),slug,qty})),attached=selected.filter(r=>phase6bReference(r.p).kind==='tabletop'),floor=selected.filter(r=>phase6bReference(r.p).kind==='equipment');assert.ok(attached.length>=2);assert.ok(floor.length>=2);
  const scene={objects:[{id:'qa-support',kind:'table',tableId:support.id,shape:support.shape,widthFt:support.widthFt,depthFt:support.depthFt,seatCount:0,x:0,y:0,tabletop:attached.map(r=>({productId:r.p.id,qty:r.qty,perSeat:false}))},...floor.flatMap(r=>{const d=equipment.find(e=>e.productId===r.p.id);assert.ok(d,r.slug);return Array.from({length:r.qty},(_,i)=>equipmentItem(d,'qa-'+r.slug+'-'+i,5+i*4,10));})]};const original=JSON.stringify(scene),summary=summarizeEvent(scene,{tables,equipment,tabletop},{includeTent:false});assert.equal(JSON.stringify(scene),original);
  const payload=buildBookingHandoff({tenant:'friendly',products,lines:summary.lines,eventDate:date,source:'phase6b_qa_no_purchase',designId:'00000000-0000-4000-8000-00000000006b',surfaceType:'grass',deliveryZip:'13116'});assert.equal(payload.items.length,chosen.length+1);for(const [slug,n] of [...chosen,['6ft-plastic-folding-table',1]])assert.equal(payload.items.find(i=>i.slug===slug)?.quantity,n,slug+' exact summary-to-booking quantity');
  const carts=[];
  for(const width of [1440,390]){const c=await context(width),p=await c.newPage();p.on('pageerror',e=>errors.push({width,error:String(e)}));await p.goto(friendlyBookingUrl(payload),{waitUntil:'domcontentloaded'});await p.waitForURL(u=>u.pathname.startsWith('/checkout'),{timeout:45000});await p.locator('label').filter({hasText:'Event starts'}).locator('select').waitFor({timeout:30000});
   const state=await p.evaluate(()=>({cart:JSON.parse(localStorage.getItem('fpr_cart')||'[]'),booking:JSON.parse(localStorage.getItem('fpr_rentsketch_booking')||'null'),overflow:document.documentElement.scrollWidth>innerWidth+1}));assert.equal(state.cart.length,payload.items.length);assert.equal(state.booking.designId,payload.designId);assert.equal(state.overflow,false);
   for(const item of payload.items){const w=website.find(w=>w.slug===item.slug),cart=state.cart.find(i=>i.id===w.id);assert.ok(cart,item.slug);assert.equal(cart.quantity,item.quantity);assert.equal(cart.price,Number(w.cost));}
   await p.locator('label').filter({hasText:'Event starts'}).locator('select').selectOption('12:00');await p.locator('label').filter({hasText:'Event ends'}).locator('select').selectOption('17:00');await p.getByRole('button',{name:/Continue to Delivery/}).click();await p.waitForURL(u=>u.pathname==='/checkout/delivery');await p.screenshot({path:OUT+'/mixed-checkout-delivery-'+width+'.png',fullPage:true});await p.reload({waitUntil:'domcontentloaded'});assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('fpr_cart')||'[]').length),payload.items.length);carts.push({width,items:payload.items,tabletopAttachedInSource:true,actualSummaryUsed:true,currentWebsitePrices:true,path:'/checkout/delivery',persisted:true});await c.close();
  }
  assert.deepEqual(errors,[]);fs.writeFileSync(OUT+'/report.json',JSON.stringify({release,identities,views,carts,unavailableForCartSmoke:missing,errors,blockedNonReadRequests:blocked,realOrdersCreated:0,realPaymentsSubmitted:0,checkedAt:new Date().toISOString()},null,2));console.log('PASS '+identities.length+' source identities; '+views.length+' live model views; '+payload.items.length+' mixed summary-to-checkout selections at desktop/mobile');
 }finally{await browser.close();}
})().catch(e=>{fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(OUT+'/failure.txt',String(e.stack||e));console.error(e);process.exit(1);});
