import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {linenSpec,linenDrapeProfile,linenCoverageLabel,productColors} from '../js/data/linen-spec.js';
import {applyTenantLinens,LINENS,linenColorHex} from '../js/data/linens.js';
import {tabletopReference} from '../js/data/tabletop-reference.js';
const require=createRequire(import.meta.url),{joinReferences,createReferenceReader}=require('../server/src/friendlyCatalogReference.js');
const product=(name,slug,extra={})=>({id:slug,name,category:'linen',external_id:'fpr:'+slug,price_per_day:17,...extra});
for(const [size,drop,pool] of [[90,1.25,0],[108,2,0],[120,2.5,0],[132,3,.5]])test(size+'-inch round cloth keeps its real nominal drop',()=>{
 const linen=product(size+' Round Polyester Tablecloth',size+'-round-polyester-tablecloth'),p=linenDrapeProfile({}, {w:5,d:5,height:2.5},linen);assert.equal(p.physicalDrop,drop);assert.equal(p.poolingFt,pool);assert.ok(p.drop<=2.5);assert.match(linenCoverageLabel(linen,{widthFt:5,depthFt:5}),/inch/);
});
for(const [w,l,table,side,end] of [[54,120,6,1,2],[72,120,6,1.75,2],[90,132,6,2.5,2.5],[90,156,8,2.5,2.5]])test(w+'x'+l+' linen dimensions use inches despite imported ft fields',()=>{
 const linen=product(w+' x '+l+' Banquet Tablecloth','cloth',{width_ft:w,length_ft:l});const p=linenDrapeProfile({}, {w:table,d:2.5,height:2.5},linen);assert.equal(p.physicalSideDrop,side);assert.equal(p.physicalEndDrop,end);
});
test('round 60 source SKU is fitted cover, not a 60-inch loose cloth',()=>{const s=linenSpec(product('White Table Linen Round 60"','white-table-linen-round-60'));assert.equal(s.kind,'stretch');assert.equal(s.roundSizeIn,undefined);assert.equal(s.tableSizeIn,60);});
test('cocktail and rectangular spandex have separate fit profiles',()=>{assert.equal(linenSpec(product('Cocktail Table Cover','cocktail-table-cover-white')).tableSizeIn,30);assert.deepEqual(linenSpec(product('Black Spandex 8ft Table Linen','black-spandex-8ft-table-linen')).fitsTableIds,['banquet-8ft']);});
test('live color choices join by unique immutable source identity only',()=>{const rows=[product('Renamed linen','sequin')],before=JSON.stringify(rows),items=[{id:'web1',slug:'sequin',colorOptions:['Rose Gold','Silver','Rose Gold']}];const out=joinReferences(rows,items,'now');assert.deepEqual(out[0].metadata.colors,['Rose Gold','Silver']);assert.equal(out[0].price_per_day,17);assert.equal(JSON.stringify(rows),before);assert.equal(out[0].metadata.referenceColorsVerified,true);assert.deepEqual(joinReferences(rows,[...items,...items],'now')[0].metadata.colors,[]);});
test('reference outage suppresses unverified catalog colors and other tenants never fetch',async()=>{let count=0;const read=createReferenceReader(async()=>{count++;throw Error('offline');},()=>1000),rows=[product('Linen','cloth')];assert.equal(await read('another-tenant',rows),rows);assert.equal(count,0);const r=await read('friendly',rows);assert.equal(r[0].metadata.referenceColorsVerified,false);assert.equal(r[0].metadata.referenceStatus,'unavailable');await read('friendly',rows);assert.equal(count,1);});
test('short-lived reference cache refreshes changed choices, never prices',async()=>{let now=0,calls=0;const read=createReferenceReader(async()=>({ok:true,json:async()=>({items:[{id:'web',slug:'cloth',colorOptions:[++calls===1?'Red':'Blue']}]})}),()=>now);const rows=[product('Linen','cloth')];assert.deepEqual((await read('friendly',rows))[0].metadata.colors,['Red']);now=61000;assert.deepEqual((await read('friendly',rows))[0].metadata.colors,['Blue']);});
test('Rose Gold gets a distinct preview and not every linen gets every color',()=>{assert.notEqual(linenColorHex('Rose Gold'),linenColorHex('White'));assert.deepEqual(productColors({metadata:{colors:['Rose Gold','Silver'],referenceColorsVerified:true}}).colors,['Rose Gold','Silver']);assert.equal(productColors({name:'Unspecified linen'}).colorsVerified,false);});
test('all supported real linen SKUs hydrate once with material/size retained',()=>{const rows=[product('120 Round Satin Tablecloth','120-round-satin-tablecloth'),product('120 Round Sequin Tablecloth','120in-round-sequin-tablecloth-rose-gold',{metadata:{colors:['Rose Gold','Silver']}}),product('White Table Linen Round 60"','white-table-linen-round-60')];applyTenantLinens({tenant:{slug:'friendly'},products:rows});for(const row of rows){const matches=LINENS.filter(l=>l.active!==false&&l.productId===row.id);assert.equal(matches.length,1);assert.ok(matches[0].spec);}assert.equal(LINENS.find(l=>l.productId===rows[0].id).spec.material,'satin');assert.equal(LINENS.find(l=>l.productId===rows[1].id).spec.material,'sequin');});
test('ambiguous legacy matches are not arbitrarily assigned; variant SKUs remain separate',()=>{const a=product('120 inch Round Polyester Tablecloth','poly-a'),b={...a,id:'poly-b',external_id:'fpr:poly-b'};applyTenantLinens({tenant:{slug:'friendly'},products:[a,b]});assert.equal(LINENS.find(l=>l.id==='linen-round-120').active,false);assert.equal(LINENS.filter(l=>l.active!==false&&l.productId).length,2);});
test('packages, aisle runners and clips are never silently turned into tablecloths',()=>{for(const name of ['Linen Tent Package','White Aisle Runner (100ft)','Plastic Linen Clips (12 Pack)','Spandex Chair Cover'])assert.equal(linenSpec({name}),null);});
test('photo identities distinguish square bread plate, fractional dinner plate, clear chargers and vessels',()=>{const ref=slug=>tabletopReference({externalId:'fpr:'+slug});assert.equal(ref('6-inch-bread-and-butter-plate').shape,'square');assert.equal(ref('10-58-dinner-plate').diameterIn,10.625);assert.equal(ref('gold-beaded-charger-plate').finish,'clear');assert.equal(ref('gold-beaded-charger-plate').beads,'gold');assert.notEqual(ref('725-oz-martini-glass').glassShape,ref('85-oz-wine-glass').glassShape);assert.equal(tabletopReference({name:'Martini Glass',externalId:'other:725-oz-martini-glass'}),null);});
