const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
(async()=>{
 const root=path.resolve(__dirname,'..'),threePath=require.resolve('three').replace('/build/three.cjs','/build/three.module.js'),THREE=await import(require('node:url').pathToFileURL(threePath));
 const draw=new Proxy({},{get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)}),context=vm.createContext({console,document:{createElement:()=>({getContext:()=>draw})}}),cache=new Map();
 const three=new vm.SyntheticModule(Object.keys(THREE),function(){for(const k of Object.keys(THREE))this.setExport(k,THREE[k]);},{context});
 function moduleFor(file){if(cache.has(file))return cache.get(file);const m=new vm.SourceTextModule(fs.readFileSync(file,'utf8'),{context,identifier:file});cache.set(file,m);return m;}
 async function load(file){const m=moduleFor(path.join(root,file));if(m.status==='unlinked')await m.link((s,r)=>s==='three'?three:moduleFor(s.startsWith('three/addons/')?path.resolve(path.dirname(threePath),'../examples/jsm',s.slice(13)):path.resolve(path.dirname(r.identifier),s)));if(m.status!=='evaluated')await m.evaluate();return m.namespace;}
 const linen=await load('js/data/linens.js'),api=await load('js/ui/equipment3d.js'),reference=await load('js/ui/tabletop-reference3d.js'),tabletop=await load('js/data/tabletop.js'),settings=await load('js/ui/tabletop3d.js');let checks=0;
 const check=(v,n)=>{assert.ok(v,n);checks++;};
 const products=[['120 Round Polyester Tablecloth','120-inch-round-polyester-tablecloth'],['90 Round Polyester Tablecloth','90-round-polyester-tablecloth'],['132 Round Polyester Tablecloth','132-round-polyester-tablecloth'],['120 Round Satin Tablecloth','120-round-satin-tablecloth'],['120 Round Sequin Tablecloth','120in-round-sequin-tablecloth-rose-gold'],['Cocktail Table Cover','cocktail-table-cover-white'],['White Table Linen Round 60"','white-table-linen-round-60'],['Black Spandex 6ft Table Linen','black-spandex-6ft-table-linen'],['54x120 Banquet Polyester Tablecloth','54x120-banquet-polyester-tablecloth']].map(([name,slug])=>({id:slug,name,category:'linen',external_id:'fpr:'+slug}));
 linen.applyTenantLinens({tenant:{slug:'friendly'},products});
 for(const l of linen.LINENS.filter(x=>x.productId&&x.active!==false)){
  const cocktail=l.spec.tableSizeIn===30,rect=l.spec.shape==='rect',item={id:l.id,tableId:cocktail?'cocktail':rect?'banquet-6ft':'round-5ft',shape:rect?'rect':'round',widthFt:cocktail?2.5:rect?6:5,depthFt:cocktail?2.5:rect?2.5:5,seatCount:0,linenId:l.id,linenProductId:l.productId,linenColor:'White'},saved=JSON.stringify(item),g=api.makeTable(item),b=new THREE.Box3().setFromObject(g);
  check(b.min.y>=-.04,'no cloth below the floor');check(b.max.y<3.56,'no oversized cloth height');check(JSON.stringify(item)===saved,'no saved layout mutation');let triangles=0;g.traverse(o=>{if(o.isMesh){check([...o.geometry.attributes.position.array].every(Number.isFinite),'finite cloth geometry');triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;}});check(triangles<40000,'bounded table mesh');check(g.children.some(o=>o.material?.userData?.finish===l.spec.material),'correct fabric finish');
 }
 for(const slug of ['glass-beaded-charger-plate','gold-beaded-charger-plate','6-inch-bread-and-butter-plate','10-58-dinner-plate','725-oz-martini-glass','10-12-oz-water-goblet','85-oz-wine-glass','glass-coffee-mug','pilsner-beer-glass','5-oz-footed-rocks-glass','glass-carafe','dinner-fork','salad-fork','cake-fork','dinner-knife','teaspoon','tablespoon-soup-spoon','serving-spoon','matching-napkins']){
  const p={productId:slug,externalId:'fpr:'+slug,name:slug},saved=JSON.stringify(p),g=reference.makeTabletopReference(p),b=new THREE.Box3().setFromObject(g);check(!!g,'supported reference '+slug);check(b.max.y<1.2&&b.max.x-b.min.x<1.5&&b.max.z-b.min.z<1.8,'sensible planning-scale object');check(JSON.stringify(p)===saved,'no product mutation');g.traverse(o=>{if(o.geometry)check([...o.geometry.attributes.position.array].every(Number.isFinite),'finite vessel or utensil');});
 }
 tabletop.TABLETOP.push({id:'napkins',productId:'napkins',name:'Matching Napkins',type:'napkin',perSeat:true,externalId:'fpr:matching-napkins'});
 const scene={id:'seated',shape:'round',widthFt:5,depthFt:5,seatCount:8,tabletop:[{productId:'napkins',perSeat:true,color:'Silver'}]},g=settings.makeTabletop(scene,2.5);check(g.children.length===8,'eight seats = eight napkins');check(g.children.every(c=>c.userData.productId==='napkins'),'correct quote identity per rendered item');
 console.log('PASS Phase 4 renderer: '+checks+' material, geometry, footprint, identity and quantity checks.');
})().catch(e=>{console.error(e);process.exitCode=1;});
