const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');const{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=root+'/qa-phase6b';
(async()=>{
 const catalog=JSON.parse(fs.readFileSync(out+'/catalog.json')),refs=JSON.parse(fs.readFileSync(out+'/references.json')).rows,products=refs.map(r=>catalog.products.find(p=>p.id===r.productId));
 const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');let bytes=fs.readFileSync(file);if(file.endsWith('catalog-preview/index.html'))bytes=Buffer.from(bytes.toString().replaceAll('https://cdn.jsdelivr.net/npm/three@0.160.0/','/tests/node_modules/three/'));res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.js')?'text/javascript':file.endsWith('.json')?'application/json':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(bytes);}catch{res.writeHead(404).end();}}).listen(8142,'127.0.0.1');
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}),page=await browser.newPage(),errors=[],views=[];
 page.on('pageerror',e=>errors.push(String(e)));await page.route('**/*',route=>{const r=route.request(),u=new URL(r.url());if(!['GET','HEAD'].includes(r.method()))return route.abort();if(u.hostname==='127.0.0.1')return route.continue();if(u.hostname==='rentsketch-api-production.up.railway.app'&&u.pathname==='/api/tenants/friendly/products')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(catalog)});return route.abort();});
 fs.mkdirSync(out+'/renders',{recursive:true});
 try{for(const width of [1000,390])for(const p of products){const slug=p.external_id.slice(4),ref=refs.find(r=>r.slug===slug).reference;
  await page.setViewportSize({width,height:760});await page.goto('http://127.0.0.1:8142/catalog-preview/?tenant=friendly&productId='+p.id,{waitUntil:'domcontentloaded'});
  if(ref.kind==='reference-only'){await page.waitForFunction(()=>document.getElementById('status').textContent==='Reference conflict — no verified model',null,{timeout:15000});assert.equal(await page.locator('canvas').count(),0);}else{await page.waitForFunction(()=>document.getElementById('visual').dataset.renderReady==='1',null,{timeout:25000});assert.equal(await page.locator('canvas').count(),1);assert.equal(await page.locator('#visual').getAttribute('data-product-id'),p.id);}
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,slug+' horizontal overflow');await page.screenshot({path:out+'/renders/'+slug+'-'+width+'.png'});
  if(width===1000&&ref.kind!=='reference-only'){const box=await page.locator('canvas').boundingBox(),before=await page.locator('canvas').screenshot();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.67,box.y+box.height*.43,{steps:9});await page.mouse.up();await page.waitForTimeout(80);const after=await page.locator('canvas').screenshot();assert.notEqual(before.toString('base64'),after.toString('base64'),slug+' actual rotatable geometry');await page.screenshot({path:out+'/renders/'+slug+'-turned.png'});}
  views.push({slug,width,mode:ref.kind==='reference-only'?'reference-conflict':'shared-3d',noOverflow:true});
 }
 await page.goto('http://127.0.0.1:8142/catalog-preview/?tenant=friendly&productId=unknown');await page.waitForFunction(()=>document.getElementById('status').textContent==='Preview unavailable');assert.equal(await page.locator('canvas').count(),0);assert.deepEqual(errors,[]);
 fs.writeFileSync(out+'/browser-report.json',JSON.stringify({views,errors,realOrdersCreated:0,realPaymentsSubmitted:0,checkedAt:new Date().toISOString()},null,2));console.log('PASS '+views.length+' real rendered desktop/mobile source comparisons, rotation checks and explicit no-model states');
 }finally{await browser.close();server.close();}
})().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(out+'/browser-failure.txt',String(e.stack||e));console.error(e);process.exit(1);});
