import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createLayoutStore} from '../js/core/layoutStore.js';
import {chairPositions,tableModelItem} from '../js/core/seating.js';
import {objectLocalDimensions,objectGroundFootprint} from '../js/core/world-space.js';
import {rentalPhotoPlacement} from '../js/core/photo-geometry.js';
import {rectFromObject} from '../js/core/geometry.js';
const source=fs.readFileSync(new URL('../script.js',import.meta.url),'utf8');
const table=(id,x=7,y=7,extra={})=>({id,kind:'table',tableId:'banquet-6ft',shape:'rect',x,y,widthFt:6,depthFt:2.5,rotationDeg:0,chairId:'plastic-white',seatCount:8,linenId:'linen-banquet-72x120',linenProductId:'qa-linen',linenColor:'Red',...extra});
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
function editor(objects){const store=createLayoutStore({tentId:'pole-20x20',objects,zones:[],aisles:[]});const c=vm.createContext({store,state:{},requireEventEditing:()=>true,layoutSpace:()=>({widthFt:30,lengthFt:30}),showLayoutNotice(){},refreshAll(){}});const a=source.indexOf('function handleEquipmentClick('),b=source.indexOf('\nfunction handleEquipmentChange(',a),m=source.indexOf('function matchTableStyle('),n=source.indexOf('\nfunction renderStatusBar(',m);assert.ok(a>=0&&b>a&&m>=0&&n>m);vm.runInContext(source.slice(m,n)+'\n'+source.slice(a,b),c);return{store,click:(role,id)=>c.handleEquipmentClick({target:{closest:()=>({dataset:{role,id}})}});}
function physical(item){assert.deepEqual(objectLocalDimensions(item),{widthFt:6,depthFt:2.5});const local=tableModelItem(item),rot=(Number(item.rotationDeg)||0)*Math.PI/180,expected=chairPositions(local),actual=chairPositions(item);assert.equal(actual.length,8);actual.forEach((p,i)=>{near(p.x,expected[i].x*Math.cos(rot)-expected[i].y*Math.sin(rot));near(p.y,expected[i].x*Math.sin(rot)+expected[i].y*Math.cos(rot));});const box=rectFromObject(item),corners=objectGroundFootprint(item);near(box.width,Math.max(...corners.map(p=>p.x))-Math.min(...corners.map(p=>p.x)));near(box.depth,Math.max(...corners.map(p=>p.y))-Math.min(...corners.map(p=>p.y)));}
test('normal editor rotations remain aligned after JSON save/reload, undo, redo and duplicate',()=>{const initial=table('one'),e=editor([initial]);for(const angle of [0,90,180,270]){if(angle)e.click('insp-rotate','one');const saved=JSON.parse(JSON.stringify(e.store.getState().objects[0]));assert.equal(saved.rotationDeg,angle);physical(saved);assert.equal(saved.linenColor,'Red');assert.equal(saved.seatCount,8);near(saved.x+saved.widthFt/2,10);near(saved.y+saved.depthFt/2,8.25);}e.store.undo();assert.equal(e.store.getState().objects[0].rotationDeg,180);e.store.redo();assert.equal(e.store.getState().objects[0].rotationDeg,270);e.click('insp-duplicate','one');const duplicate=e.store.getState().objects[1];assert.notEqual(duplicate.id,'one');physical(duplicate);assert.equal(duplicate.linenProductId,'qa-linen');e.click('insp-rotate','one');assert.deepEqual(e.store.getState().objects[0],initial);});
test('Use chairs and linen on matching tables never changes physical orientation or placement',()=>{const e=editor([table('source'),table('target',12,11,{widthFt:2.5,depthFt:6,rotationDeg:90,linenColor:'White',chairId:'resin-white'}),table('unrelated',20,20,{tableId:'banquet-8ft',widthFt:8})]);const before=structuredClone(e.store.getState().objects);e.click('insp-match-tables','source');for(const [i,item] of e.store.getState().objects.entries()){for(const k of ['id','tableId','x','y','widthFt','depthFt','rotationDeg','seatCount'])assert.equal(item[k],before[i][k]);if(i<2){assert.equal(item.linenColor,'Red');assert.equal(item.chairId,'plastic-white');physical(item);}else assert.deepEqual(item,before[i]);}});
test('independent photo orientation retains the table local dimensions without mutating the save',()=>{const saved=table('photo',10,12,{widthFt:2.5,depthFt:6,rotationDeg:90}),before=structuredClone(saved),tent={widthFt:20,lengthFt:20},site={widthFt:60,lengthFt:60};for(const angle of [0,30,45,90,180,270]){const result=rentalPhotoPlacement(saved,tent,site,{x:20,y:20,rotationDeg:angle});physical(result);assert.equal(result.rotationDeg,angle+90);const independent=rentalPhotoPlacement({...saved,photoPlacement:{x:33,y:44,rotationDeg:angle}},tent,site,{x:20,y:20,rotationDeg:90});physical(independent);assert.equal(independent.rotationDeg,angle);assert.equal(independent.x,33);assert.equal(independent.y,44);}assert.deepEqual(saved,before);});
