// Customer presentation uses only explicit public scene fields. No contact
// information, access credentials, or private crew notes are rendered here.
(function () {
  'use strict';
  var panel = null, model = null, lastFocus = null, busy = false, generation = 0;
  function bridge() { return window.FriendlyBridge || {}; }
  function esc(value) { return String(value ?? '').replace(/[&<>"']/g, function (c) { return { '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]; }); }
  function allowed() { var slug = window.RENTSKETCH_TENANT_SLUG || new URLSearchParams(location.search).get('tenant') || 'generic'; return !window.RENTSKETCH_SHARED_READONLY && (!['friendly','generic'].includes(slug) || window.RentSketchEventPass?.canEdit?.() === true); }
  function identity() { return [window.RENTSKETCH_TENANT_SLUG || '',window.RentSketchDashboardSession?.identity?.() || '',window.RentSketchAutosave?.getDesignId?.() || ''].join('|'); }
  function imageUrl(value) { return typeof value === 'string' && /^data:image\/(png|jpeg|webp);base64,[a-z0-9+/=\s]+$/i.test(value) ? value : null; }
  function filename(title) { return String(title || 'event-plan').normalize('NFKD').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,70) || 'event-plan'; }
  function catalogs() { var b=bridge(); return {tables:b.TABLES||[],chairs:b.CHAIRS||[],equipment:b.EQUIPMENT||[],inflatables:b.INFLATABLES||[],accessories:b.ACCESSORIES||[]}; }
  function caption(scene,mode) { return mode === 'photo' ? 'Camera-matched photo preview · perspective and scale are estimates.' : scene.backgroundPhoto && scene.venueScan ? 'Captured venue preview · reconstructed geometry and dimensions are estimates.' : scene.backgroundPhoto ? 'Modeled venue layout · confirm dimensions against your property.' : 'Illustrative event model · surroundings and decorative details are for preview.'; }
  function fallbackSnapshot(scene) {
    var tent=(bridge().TENTS||[]).find(function(t){return t.id===scene.tentId;}) || {isSite:true,widthFt:scene.siteWidthFt||50,lengthFt:scene.siteLengthFt||60};
    if (scene.siteLayout) tent=Object.assign({},tent,{planningArea:{widthFt:Math.max(scene.siteWidthFt||50,tent.widthFt),lengthFt:Math.max(scene.siteLengthFt||60,tent.lengthFt)}});
    return Object.assign({},scene,{tent:tent,photoSite:{widthFt:Math.max(scene.siteWidthFt||50,tent.widthFt+20,50),lengthFt:Math.max(scene.siteLengthFt||60,tent.lengthFt+20,60)}});
  }
  async function prepare() {
    if (!allowed()) throw new Error('Open your event access to export this layout.');
    var owner=identity(),b=bridge(),scene=b.getScene?.();
    if(!scene) throw new Error('Your layout is still loading. Try again in a moment.');
    var capture=b.capturePresentation?await b.capturePresentation():{image:document.querySelector('.review-layout-visual img')?.src,mode:scene.viewMode};
    var module=await import('./presentation-plan.js');
    if (!allowed() || owner!==identity()) throw new Error('Event access changed. Reopen the project before exporting.');
    var plan=module.presentationPlan(capture?.snapshot || b.getPresentationSnapshot?.() || fallbackSnapshot(scene),catalogs());
    var project=window.RentSketchAutosave?.getState?.().project || {},name=project.projectName||scene.eventName||'Your event plan';
    var lines=(b.computeLineItems?.()||[]).map(function(line){return {label:String(line.label||'Rental'),qty:Number(line.qty)||0};});
    var warnings=Array.from(new Set((b.getChecks?.()||[]).filter(function(c){return c.severity!=='info';}).map(function(c){return c.message;}).filter(Boolean)));
    return {title:name,company:window.ACTIVE_TENANT?.name||'RentSketch',date:typeof scene.customer?.date==='string'?scene.customer.date.slice(0,10):'',guests:Math.max(0,Number(scene.guestCount)||0),seats:(scene.objects||[]).reduce(function(n,item){return n+(Number(item.seatCount)||0);},0),cover:imageUrl(capture?.image),mode:capture?.mode||scene.viewMode,caption:capture?.caption||caption(scene,capture?.mode||scene.viewMode),plan:plan,lines:lines,warnings:warnings,created:new Date().toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}),owner:owner};
  }
  function documentHtml(data) {
    var legend=data.plan.labels.map(function(item){return '<li><span>'+item.number+'</span>'+esc(item.label)+'</li>';}).join('');
    return '<article class="rs-presentation-document"><section class="rs-presentation-page rs-presentation-cover"><header><p class="rs-presentation-brand">'+esc(data.company)+' <span>· RENTSKETCH</span></p><p class="rs-presentation-kicker">YOUR EVENT, ENVISIONED</p><h1>'+esc(data.title)+'</h1><div class="rs-presentation-facts">'+(data.date?'<span>'+esc(data.date)+'</span>':'')+(data.guests?'<span>'+esc(data.guests)+' guests</span>':'')+(data.seats?'<span>'+esc(data.seats)+' planned seats</span>':'')+'</div></header>'+(data.cover?'<figure class="rs-presentation-hero"><img src="'+esc(data.cover)+'" alt="Current event layout view"><figcaption>'+esc(data.caption)+'</figcaption></figure>':'<figure class="rs-presentation-hero rs-presentation-vector">'+data.plan.svg+'<figcaption>Event floor plan · placement shown in feet.</figcaption></figure>')+'<footer><span>Prepared '+esc(data.created)+'</span><span>Planning draft</span></footer></section><section class="rs-presentation-page"><div class="rs-presentation-section-title"><p class="rs-presentation-kicker">THE ARRANGEMENT</p><h2>Room for your event</h2><p>'+esc(data.plan.widthFt)+' × '+esc(data.plan.lengthFt)+' ft planning area'+(data.plan.estimated?' · estimated photo placement':'')+'</p></div><div class="rs-presentation-plan">'+data.plan.svg+'</div><ol class="rs-presentation-legend">'+legend+'</ol><p class="rs-presentation-note">Diagram orientation is marked at the front edge. Confirm actual site dimensions, access paths and installation clearances with your rental company.</p></section><section class="rs-presentation-page"><div class="rs-presentation-section-title"><p class="rs-presentation-kicker">THE DETAILS</p><h2>Your rental selections</h2><p>Quantities from this layout. Confirm availability and your final booking with '+esc(data.company)+'.</p></div><table class="rs-presentation-items"><thead><tr><th>Rental</th><th>Quantity</th></tr></thead><tbody>'+(data.lines.length?data.lines.map(function(line){return '<tr><td>'+esc(line.label)+'</td><td>'+esc(line.qty)+'</td></tr>';}).join(''):'<tr><td colspan="2">No rental selections in this layout.</td></tr>')+'</tbody></table>'+(data.warnings.length?'<div class="rs-presentation-checks"><h3>Placement to review</h3><ul>'+data.warnings.map(function(warning){return '<li>'+esc(warning)+'</li>';}).join('')+'</ul></div>':'')+'<p class="rs-presentation-note">This presentation is a planning draft. Availability, dimensions, anchoring, weather conditions and installation requirements must be confirmed by the rental company. People, landscaping and decorative details shown in the preview are included only when listed in your booking.</p></section></article>';
  }
  function close() { generation++; window.removeEventListener('afterprint',afterPrint); document.body.classList.remove('rs-print-presentation','rs-presentation-open'); panel?.remove(); panel=null;model=null;lastFocus?.focus?.(); }
  function afterPrint() { document.body.classList.remove('rs-print-presentation'); }
  function status(text) { var node=panel?.querySelector('[data-presentation-status]');if(node)node.textContent=text||''; }
  function render() {
    if(!panel||!model)return;
    var views=bridge().getPresentationViews?.()||[],coverId=bridge().getScene?.().presentationCoverId,canSave=['3d','photo'].includes(model.mode);
    panel.innerHTML='<div class="rs-presentation-dialog" role="dialog" aria-modal="true" aria-labelledby="rsPresentationTitle" tabindex="-1"><header class="rs-presentation-toolbar"><div><h2 id="rsPresentationTitle">Event presentation</h2><p>Your current view, floor plan and rental list.</p></div><div><button type="button" data-presentation-action="download">Download image</button><button type="button" data-presentation-action="print">Print / save PDF</button><button type="button" data-presentation-action="close" aria-label="Close presentation">×</button></div></header><details class="rs-presentation-views"'+(window.innerWidth>650?' open':'')+'><summary>Saved views &amp; opening angle <span>'+views.length+' of 6</span></summary><div class="rs-presentation-view-controls"><label>Cover view<select data-presentation-view><option value="">Current view</option>'+views.map(function(view){return '<option value="'+esc(view.id)+'">'+esc(view.name)+(view.id===coverId?' · Opening view':'')+'</option>';}).join('')+'</select></label><button type="button" data-presentation-action="cover-view" disabled>Use as opening view</button><button type="button" data-presentation-action="delete-view" disabled>Remove saved view</button>'+(canSave&&bridge().savePresentationView?'<form data-presentation-save><label class="rs-presentation-sr" for="rsPresentationViewName">Name this view</label><input id="rsPresentationViewName" name="name" maxlength="60" placeholder="Entrance, reception, table detail" required><button type="submit"'+(views.length>=6?' disabled':'')+'>Save this view</button></form>':'')+'<p>Choose your angle in the designer before opening this presentation. Up to six saved views travel with your project.</p></div></details><p role="status" aria-live="polite" data-presentation-status></p><div class="rs-presentation-scroll">'+documentHtml(model)+'</div></div>';
  }
  function downloadBlob(blob,name) { var url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},30000); }
  function loadImage(src) { return new Promise(function(resolve,reject){var img=new Image(),timer=setTimeout(function(){reject(new Error('The layout image took too long to prepare. Try again.'));},10000);img.onload=function(){clearTimeout(timer);resolve(img);};img.onerror=function(){clearTimeout(timer);reject(new Error('The layout image could not be prepared. Return to the designer and try again.'));};img.src=src;}); }
  async function imageBlob(data) {
    var src=data.cover || 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(data.plan.svg),img=await loadImage(src);
    var canvas=document.createElement('canvas'),scale=Math.min(1,2400/Math.max(img.naturalWidth,img.naturalHeight));canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));
    var ctx=canvas.getContext('2d');if(!ctx)throw new Error('Image export is unavailable in this browser. Use Print / save PDF.');ctx.fillStyle='#fbfcf9';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);
    return new Promise(function(resolve,reject){try{canvas.toBlob(function(blob){if(blob)resolve(blob);else reject(new Error('Image export could not finish. Use Print / save PDF.'));},'image/png');}catch(error){reject(new Error('The browser could not export this image. Use Print / save PDF.'));}});
  }
  async function download(data) { if(!allowed())return;var selected=data||await prepare(),blob=await imageBlob(selected);if(!allowed()||selected.owner!==identity())throw new Error('Event access changed before export.');downloadBlob(blob,filename(selected.title)+(selected.cover?'-view':'-floor-plan')+'.png'); }
  async function print() {
    if(!panel||!model||!allowed()||model.owner!==identity())return;
    await Promise.all(Array.from(panel.querySelectorAll('.rs-presentation-document img')).map(function(img){return img.complete&&img.naturalWidth?Promise.resolve():loadImage(img.src);}));
    if(!panel||!model||!allowed()||model.owner!==identity())return;
    document.body.classList.remove('rs-print-crew');document.body.classList.add('rs-print-presentation');window.addEventListener('afterprint',afterPrint,{once:true});window.print();
  }
  async function act(work) { if(busy)return;busy=true;status('Preparing your presentation…');panel?.querySelectorAll('button,input,select').forEach(function(el){el.disabled=true;});try{await work();status('');}catch(error){status(error.message||'Please try again.');}finally{busy=false;panel?.querySelectorAll('button,input,select').forEach(function(el){el.disabled=false;});var remove=panel?.querySelector('[data-presentation-action=delete-view]'),save=panel?.querySelector('[data-presentation-save] button');if(remove)remove.disabled=!panel.querySelector('[data-presentation-view]')?.value;var cover=panel?.querySelector('[data-presentation-action=cover-view]');if(cover)cover.disabled=!panel.querySelector('[data-presentation-view]')?.value||!bridge().setPresentationCover;if(save)save.disabled=(bridge().getPresentationViews?.()||[]).length>=6;if(panel&&!panel.contains(document.activeElement))panel.querySelector('[role=dialog]').focus({preventScroll:true});} }
  async function open() {
    if(!allowed())return window.RentSketchEventPass?.requestAccess?.();
    var epoch=++generation,focused=document.activeElement,prepared=await prepare();if(epoch!==generation)return;
    if(!panel){lastFocus=focused;bridge().closeDrawer?.();panel=document.createElement('div');panel.id='rsPresentation';document.body.appendChild(panel);document.body.classList.add('rs-presentation-open');
      panel.addEventListener('click',function(event){var action=event.target.closest('[data-presentation-action]')?.dataset.presentationAction;if(event.target===panel||action==='close')return close();if(action==='download')act(function(){return download(model);});if(action==='print')act(print);if(action==='cover-view'){var coverId=panel.querySelector('[data-presentation-view]')?.value;if(coverId)act(async function(){if(await bridge().setPresentationCover?.(coverId)===false)throw new Error('This opening view could not be saved.');render();panel.querySelector('[data-presentation-view]').value=coverId;});}if(action==='delete-view'){var id=panel.querySelector('[data-presentation-view]')?.value;if(id)act(async function(){await bridge().deletePresentationView?.(id);render();});}});
      panel.addEventListener('change',function(event){if(!event.target.matches('[data-presentation-view]'))return;if(!event.target.value){panel.querySelectorAll('[data-presentation-action=cover-view],[data-presentation-action=delete-view]').forEach(function(button){button.disabled=true;});return;}var id=event.target.value;act(async function(){if(await bridge().reopenPresentationView?.(id)===false)throw new Error('This view is unavailable in the current venue.');model=await prepare();render();var select=panel?.querySelector('[data-presentation-view]');if(select)select.value=id;});});
      panel.addEventListener('submit',function(event){if(!event.target.matches('[data-presentation-save]'))return;event.preventDefault();var name=event.target.elements.name.value.trim();if(!name)return;act(async function(){var saved=await bridge().savePresentationView(name);if(saved===false)throw new Error('This view could not be saved. Choose a 3D or matched photo view.');render();if(saved?.id)panel.querySelector('[data-presentation-view]').value=saved.id;status('View saved with this project.');});});
      panel.addEventListener('keydown',function(event){if(event.key==='Escape'){event.stopPropagation();close();return;}if(event.key!=='Tab')return;var nodes=Array.from(panel.querySelectorAll('button:not(:disabled),select:not(:disabled),input:not(:disabled)')),first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===panel.querySelector('[role=dialog]'))){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}});
    }
    model=prepared;render();panel.querySelector('[role=dialog]').focus();
  }
  window.addEventListener('resize',function(){if(window.innerWidth<=650)panel?.querySelector('.rs-presentation-views')?.removeAttribute('open');});
  window.addEventListener('rentsketch:dashboardSessionChanged',close);window.addEventListener('pagehide',close);
  window.RentSketchPresentation={open:open,close:close,download:download,print:print,prepare:prepare,documentHtml:documentHtml};
})();
